FROM tensorflow/tensorflow:nightly-gpu-jupyter

RUN apt-get install wget

RUN pip install SciPy

RUN pip install kaggle

RUN pip install opendatasets

RUN pip install pandas

RUN pip install firebase_admin